# Change these first
owner: Moore-Legal-Technology-Ltd # Your GitHub username
repo: uptimes # Your Github repository name

# Add your sites here
sites:
  - name: Moore Legal Technology
    url: https://www.moorelegaltechnology.co.uk
  - name: Your Law Firm Your Succes
    url: https://yourlawfirmsuccess.co.uk
  - name: Gary Mathews
    url: https://www.gary.ie

status-website:
  css: ".logo img {width:180px;height:auto;}"
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.moorelegaltechnology.co.uk
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://www.moorelegaltechnology.co.uk/images/logo.png
  name: Uptime Stats
  introTitle: "**Site Uptimes**"
  introMessage: Up time monitor for sites we are interested in monitoring. 
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
